### ISSUE TITLE
Making ssplit-cpp self contained

### ISSUE THREAD

**Issue by abhi-agg** [ugermann/ssplit-cpp#6]
It is not an issue but might be treated as a feature request :)

Right now, ssplit-cpp requires users to have pcre/pcrecpp library already installed on the system.
How about adding pcre/pcrecpp sources as 3rd party dependency in the tree and compile everything from sources? It will make ssplit-cpp self contained and eliminate the need of installing anything before using it.

**Comment by ugermann** [comment]
I'd rather not. Compiling pcre2 also requires ICU, so we'd have to install that as well.

**Comment by ugermann** [comment]
pcre2 is now an external project. 

For wasm compilation do 

```
/path/to/emsdk/upstream/emscripten/emcmake cmake /path/to/ssplit-cpp/ -D USE_INTERNAL_PCRE2=on
```

**Comment by jerinphilip** [comment]
Reopen. WASM builds are failing. This shouldn't happen if compile contained is working. Probably a CMake thing.

```make
em++: warning: USE_PTHREADS + ALLOW_MEMORY_GROWTH may run non-wasm code slowly, see https://github.com/WebAssembly/design/issues/1271 [-Wpthreads-mem-growth]
wasm-ld: error: unknown file type: libpcre2_8_la-pcre2_compile.o
em++: error: '/mnt/Storage/jphilip/bergamot/emsdk/upstream/bin/wasm-ld -o bergamot-translator-worker.wasm CMakeFiles/bergamot-translator-worker.dir/bindings/TranslationModelBindings.cpp.o CMakeFiles/bergamot-translator-worker.dir/bindings/TranslationRequestBindings.cpp.o CMakeFiles/bergamot-translator-worker.dir/bindings/TranslationResultBindings.cpp.o ../src/translator/libbergamot-translator.a ../libmarian.a ../3rd_party/marian-dev/src/3rd_party/sentencepiece/src/libsentencepiece.a ../3rd_party/marian-dev/src/3rd_party/intgemm/libintgemm.a ../3rd_party/marian-dev/src/3rd_party/onnxjs/src/wasm-ops/libonnx-sgemm.a ../libssplit.a ../3rd_party/ssplit-cpp/lib/libpcre2-8.a -L/mnt/Storage/jphilip/bergamot/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten --whole-archive /mnt/Storage/jphilip/bergamot/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libembind-rtti.a --no-whole-archive /mnt/Storage/jphilip/bergamot/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libgl-mt.a /mnt/Storage/jphilip/bergamot/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libal.a /mnt/Storage/jphilip/bergamot/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libhtml5.a /mnt/Storage/jphilip/bergamot/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc-mt.a /mnt/Storage/jphilip/bergamot/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libcompiler_rt-mt.a /mnt/Storage/jphilip/bergamot/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc++-mt-noexcept.a /mnt/Storage/jphilip/bergamot/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc++abi-mt-noexcept.a /mnt/Storage/jphilip/bergamot/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libdlmalloc-mt.a /mnt/Storage/jphilip/bergamot/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc_rt_wasm.a /mnt/Storage/jphilip/bergamot/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libsockets-mt.a -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --lto-legacy-pass-manager --allow-undefined --import-memory --shared-memory --strip-debug --export main --export stackSave --export stackRestore --export stackAlloc --export __wasm_call_ctors --export __errno_location --export __emscripten_pthread_data_constructor --export __pthread_tsd_run_dtors --export _emscripten_call_on_thread --export _emscripten_do_dispatch_to_thread --export _emscripten_main_thread_futex --export _emscripten_thread_init --export emscripten_current_thread_process_queued_calls --export _emscripten_allow_main_runtime_queued_calls --export emscripten_futex_wake --export emscripten_get_global_libc --export emscripten_main_browser_thread_id --export emscripten_main_thread_process_queued_calls --export emscripten_register_main_browser_thread_id --export emscripten_run_in_main_runtime_thread_js --export emscripten_stack_set_limits --export emscripten_sync_run_in_main_thread_2 --export emscripten_sync_run_in_main_thread_4 --export emscripten_tls_init --export pthread_self --export memalign --export malloc --export free --export setThrew --export _get_tzname --export _get_daylight --export _get_timezone --export-table -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=2147483648 --global-base=1024' failed (1)
wasm/CMakeFiles/bergamot-translator-worker.dir/build.make:140: recipe for target 'wasm/bergamot-translator-worker.js' failed
make[3]: *** [wasm/bergamot-translator-worker.js] Error 1
make[3]: Leaving directory '/mnt/Storage/jphilip/bergamot/build/wasm'
CMakeFiles/Makefile2:1064: recipe for target 'wasm/CMakeFiles/bergamot-translator-worker.dir/all' failed
make[2]: *** [wasm/CMakeFiles/bergamot-translator-worker.dir/all] Error 2
make[2]: Leaving directory '/mnt/Storage/jphilip/bergamot/build/wasm'
/mnt/Storage/jphilip/bergamot/build/wasm/Makefile:155: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/mnt/Storage/jphilip/bergamot/build/wasm'
Makefile:51: recipe for target 'wasm' failed
```

**Comment by jerinphilip** [comment]
@ugermann [Here](https://gist.github.com/jerinphilip/f1caac37ac1eced45e6e9d94380bc4d0)'s the Makefile I'm using to build wasm on var (should hopefully work out of the box, options are already set in there).  Adjust the variables and 

```bash
make first-setup
make wasm
make native
```

to reproduce.

**Comment by ugermann** [comment]
I'm new to emscripten. Judging by what I read online, the following is the recommended way of doing things, and it works on vor. 

# Step 1: Install emsdk if necessary
(see: https://github.com/emscripten-core/emsdk)
For convenience, I assume that you install emsdk in `/path/to/emsdk` 
```
cd /path/to
git clone https://github.com/emscripten-core/emsdk
cd emsdk
./emsdk install latest
./emsdk activate latest
```
Needless to say, emscripten should be provided globally on Valhalla, so that this step (and the next step) should not be required. Since Valhalla is 4 years behind the rest of the world, things are a bit tricky. In particular, Ubuntu 16.04 shipped with python 3.5, but support has ended, and many reasonably up-to-date tools require python3.6. I've manually installed newer versions of python on some but not all machines, so currently it's a bit hit-and-miss. The problem is that the ancient version of puppet that we are using (again: Ubuntu 16.04) does not support certain features in newer versions of puppet that would allow us to upgrade python3 across Valhalla easily. I've upgraded python on vor and made python3 point to version 3.8 on vor, so things should work there. It may not work on other machines (run `python3 --version` to check; I think anything >= 3.6 should be fine; let me know if a machine is still at 3.5 ). To cut a long discussion short: the following should work on vor.I admit that I haven't looked at your Makefile, but I think following the recommended procedure is the sounder approach in the long run.

# Step 2: source emsdk environment
I make this a separate step because you want to make sure that emsdk is available on all machines. With our horrible setup on Valhalla, there's still no good way of having stuff available on all machines without a considerable amount of fiddling. 
```
source /path/to/emsdk/emsdk_env.sh
```
You now should have emcmake and emmake available in your `${PATH}`. Make sure that the python version is 3.6 or above or things will fail.

# Step 3: Configure and compile ssplit-cpp with cmake for wasm
```
cd /path/to/your/ssplit-cpp
rm -rf build.wasm # clean slate
mkdir build.wasm # our working directory
cd build.wasm
emcmake cmake -DUSE_INTERNAL_PCRE2=ON
emmake make -j $(( $(nproc) - 2 ))
```

On a marginal note: vor is just about one of the slowest machines in terms of CPU speed that we have (knl). Is there any particular reason that you chose vor over another machines? Just wondering ...

**Comment by jerinphilip** [comment]
I'm on `var`, not `vor`. It's a new gen Intel machine which I'm using to prototype the CPU Inference and the new translator replacement. WASM sets up emsdk for me. I have `USE_INTERNAL_PCRE2=on` enabled with WASM ([ref](https://github.com/browsermt/bergamot-translator/commit/d304165d8b10016feda9efe2ab550de94266c43a)).

Find my experimental branch at [browsermt/bergamot-translator@jp/ssplit-pcre2-exps](https://github.com/browsermt/bergamot-translator/tree/jp/ssplit-pcre2-exps). I'm checking changes, you can parameterize the Makefile giving branch as `jp/ssplit-pcre2-exps` after configuring the directories.

Note that the version I PR-d, which includes CMakeLists.txt from the download builds successfully with WASM and not the current master, so I'm guessing if the variables are accurate it has something to do with the changes in your modifications.

**Comment by jerinphilip** [comment]
@ugermann To add, the problem is not likely that emscripten cannot compile your changes, it's that the variables don't probably propagate accurately in case of a compilation include. In this sense, ssplit-cpp is not exactly self contained with PCRE2 such that it can be directly included as `3rd-party/x` in other projects. I see you're using a non-CMakeLists.txt based solution through ./configure builds in your changes. 

(Look at the makefile. My first-setup gets me emscripten builds/env).

**Comment by abhi-agg** [comment]
@ugermann Adding pcre2 sources in 3rd-party folder will really clean up [this part of your CMakeLists.txt](https://github.com/ugermann/ssplit-cpp/blob/master/CMakeLists.txt#L26-L72) file. I can do that and submit a PR. What do you say?

**Comment by ugermann** [comment]
Done by pulling in pcre2 when required via cmake ExternalProject.
